/**
 * Öffentliche Namen für die MG Gönnervereinigung auf /sponsoring.
 * Einträge hier ergänzen oder entfernen; die Seite sortiert für die Anzeige alphabetisch (de-CH).
 */
export const goennervereinigungMemberNames: string[] = [
  "Patrick Falk",
  "Marc Gilardi",
  "Denise Spescha",
  "Claudio Casutt",
  "Gabriela Hürzeler",
  "Luzi Willi",
  "Ines Danuser",
  "Michel Burckhardt",
  "Philippe Freiburghaus",
  "Marc Flückiger",
  "Roman Fümberger",
  "Hans Peter Uster",
  "Klemens Binswanger",
  "Patrik Stöckli",
  "Fam. Meyrat",
  "Serge Mauser",
  "Alexander Grupp",
  "Reto Hartmann",
  "Claudio Blaesi",
  "Gilbert Vollmer",
  "Emanuele Giulini",
  "Marco Hürzeler",
  "Franz Allenspach",
  "Nino Ziegler / TheGolfers",
  "Marco Membrini",
  "Patrick Spescha",
  "Mario Padrun",
  "Karin Fischer-Olgiati",
  "Daniel Sigrist",
  "Reto Lendenmann / JLindeberg",
  "Marco De-Steffani",
  "Golf Domat-Ems",
  "Elvira Knecht",
  "Mike Fernström",
  "Peter Brunner",
  "Werner & Alexa Steinauer",
  "Franco Cavegn / Unic Talent",
  "Marco Walser",
  "Mario Candrian (fitnesstower medical AG)",
  "Leandro De Gani (De Gani Immobilien)",
  "Barbara Wehrle",
  "Markus Theus",
  "Thomas Pool",
  "Alfons Livers",
  "Rolf Schönbächler",
  "Roland & Corinne Anderegg",
];
